import {travelFixture} from './travel-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Combat} from '../game/src/combat-model.js';
import {Progression,validSave,saveStore,SMITH} from '../game/src/progression.js';
import {Campaign} from '../game/src/campaign.js';
const setup=(saved=null)=>{const m=new Combat(),p=new Progression(saved),c=new Campaign(p,m);p.restore(m);return{m,p,c};};
const step=(m,t)=>{for(let n=0;n<Math.ceil(t*60);n++)m.update(1/60);};
function clear({m,p,c}){if(m.region!==3){m.damageShard(m.shard.maxHp);step(m,1.6);}for(const e of m.enemies)m.damageEnemy(e,e.maxHp);p.events(m.consume(),m);c.observe();}

test('legacy save migrates without losing inventory, currency or partial encounter',()=>{const m=new Combat(),p=new Progression();m.damageShard(100);p.events(m.consume(),m);m.damageEnemy(m.enemies[0],999);p.events(m.consume(),m);const old=p.snapshot(m);assert.equal(old.campaign,undefined);assert(validSave(old));const s=setup(old);assert.equal(s.m.shard.hp,150);assert.equal(s.m.enemies[0].hp,0);assert.deepEqual(s.p.data.items,old.items);assert.equal(s.p.data.gold,old.gold);assert.equal(s.c.region,0);assert(validSave(s.p.snapshot(s.m)));});
test('quest gates reject locked, out-of-range and unsafe travel',()=>{const s=setup();for(const i of [-1,1,2,3,4,NaN])assert(!s.c.travel(i));clear(s);s.m.player.z=0;s.m.player.action={};assert(!s.c.travel(1));s.m.player.action=null;assert(travelFixture(s.c,1));s.m.player.z=-25;assert(!s.c.travel(0));s.m.player.z=11;assert(travelFixture(s.c,0));});
test('quest reward is once only, including after reload and revisiting',()=>{const s=setup();clear(s);const gold=s.p.data.gold,xp=s.p.data.xp;assert(!s.c.observe());assert.equal(s.p.data.gold,gold);assert.equal(s.p.data.xp,xp);const r=setup(s.p.snapshot(s.m));assert(!r.c.observe());assert.equal(r.p.data.gold,gold);assert(travelFixture(r.c,1));assert(travelFixture(r.c,0));assert(!r.c.observe());assert.equal(r.p.data.gold,gold);});
test('regional drops and dead guardians persist across travel without item-ID collisions',()=>{const s=setup();clear(s);const drops=structuredClone(s.p.data.drops);assert.equal(drops.length,25);assert(travelFixture(s.c,1));assert.equal(s.p.data.drops.length,0);clear(s);assert(validSave(s.p.snapshot(s.m)));assert(travelFixture(s.c,0));assert.deepEqual(s.p.data.drops,drops);assert(s.m.complete);const drop=drops.find(d=>d.item);Object.assign(s.m.player,{x:drop.x,z:drop.z});assert(s.p.collect(s.m.player));assert(travelFixture(s.c,1));assert(travelFixture(s.c,0));assert(!s.p.data.drops.some(d=>d.id===drop.id));assert(validSave(s.p.snapshot(s.m)));});
test('three shards open the boss; only four completed quests finish the campaign',()=>{const s=setup();for(let i=0;i<3;i++){assert.equal(s.m.region,i);assert(!s.c.complete);clear(s);assert(travelFixture(s.c,i+1));assert(validSave(s.p.snapshot(s.m)));}assert.equal(s.c.telemetry().shards,3);assert.equal(s.m.enemies[0].kind,'boss');assert.equal(s.m.enemies.length,1);assert.equal(s.m.shard.hp,0);assert(!s.c.complete);clear(s);assert(s.c.complete);assert.equal(s.p.data.drops[0].item.rarity,'rare');assert(validSave(s.p.snapshot(s.m)));assert(setup(s.p.snapshot(s.m)).c.complete);});
test('death retry retains region and earned rewards, not surviving enemy damage',()=>{const s=setup();clear(s);travelFixture(s.c,1);s.m.damageEnemy(s.m.enemies[0],999);s.m.damageEnemy(s.m.enemies[1],10);s.p.events(s.m.consume(),s.m);const gear=structuredClone(s.p.data.items);s.m.player.hp=1;s.m.hurtPlayer(50);s.p.events(s.m.consume(),s.m);const gold=s.p.data.gold;s.c.retry();assert.equal(s.c.region,1);assert.equal(s.m.player.z,11);assert.equal(s.m.player.hp,s.m.player.maxHp);assert.equal(s.p.data.gold,gold);assert.equal(s.m.enemies[0].hp,0);assert.equal(s.m.enemies[1].hp,s.m.enemies[1].maxHp);assert.deepEqual(s.p.data.items,gear);assert(validSave(s.p.snapshot(s.m)));});
test('smith is only available in Hearthstead; new expedition resets quests but not gear',()=>{const s=setup();clear(s);travelFixture(s.c,1);Object.assign(s.m.player,SMITH);assert(!s.p.nearSmith(s.m.player));const gold=s.p.data.gold;s.p.nextRun(s.m);assert.equal(s.c.region,0);assert.deepEqual(s.c.data.cleared,[false,false,false,false]);assert.equal(s.p.data.gold,gold);assert.equal(s.p.data.items.length,4);assert(validSave(s.p.snapshot(s.m)));});
test('schema rejects broken campaign state and duplicate loot across regions',()=>{const s=setup();clear(s);travelFixture(s.c,1);const good=s.p.snapshot(s.m);assert(validSave(good));for(const mutate of [d=>d.campaign.region=9,d=>d.campaign.cleared[0]=false,d=>d.campaign.regions[1]={},d=>d.campaign.regions[0].world.shardHp=100,d=>d.campaign.cleared[3]=true,d=>d.drops.push(structuredClone(d.campaign.regions[0].drops.find(x=>x.item))),d=>d.campaign.regions[0].claimed.push(99)]){const bad=structuredClone(good);mutate(bad);assert(!validSave(bad));}});
test('malformed campaign save remains protected from writes',()=>{let raw=JSON.stringify({...setup().p.data,campaign:{region:99}});const before=raw,store=saveStore({getItem:()=>raw,setItem:(k,v)=>raw=v});assert.equal(store.load(),null);const s=setup();assert(!store.write(s.p.snapshot(s.m)));assert.equal(raw,before);});
test('boss windup is visible, does not instantly hit, and survives stagger',()=>{const m=new Combat();m.reset(3);const e=m.enemies[0];Object.assign(m.player,{x:e.x,z:e.z+2.9});step(m,.05);assert.equal(e.phase,'windup');assert.equal(m.player.hp,120);m.damageEnemy(e,10,2);step(m,.2);assert.equal(e.phase,'windup');assert.equal(m.player.hp,120);step(m,1);assert(m.player.hp<120);});
test('boss sweep can be dodged and slam damages only within its warning radius',()=>{const m=new Combat();m.reset(3);const e=m.enemies[0];Object.assign(m.player,{x:e.x,z:e.z+2.9});step(m,.05);Object.assign(m.player,{x:e.x,z:e.z-6});step(m,1.1);assert.equal(m.player.hp,120);e.phase='idle';e.attackCount=1;Object.assign(m.player,{x:e.x,z:e.z+2});step(m,.02);assert.equal(e.attackKind,'slam');assert.equal(e.phase,'windup');m.player.z=e.z+5;step(m,1.7);assert.equal(m.player.hp,120);});
test('boss enrages once at half health and does not act after death',()=>{const m=new Combat();m.reset(3);const e=m.enemies[0];m.damageEnemy(e,e.maxHp/2+1);m.consume();step(m,.1);assert(e.enraged);assert.equal(m.consume().filter(e=>e.type==='notice').length,1);step(m,1);assert.equal(m.consume().filter(e=>e.type==='notice').length,0);m.damageEnemy(e,e.maxHp);step(m,3);assert(m.complete);assert.equal(m.kills,1);});
