import test from 'node:test';
import assert from 'node:assert/strict';
import { Combat, WEAPONS, inArc } from '../game/src/combat-model.js';

const step=(m,seconds,input={x:0,z:0,attack:false,aim:0})=>{for(let i=0;i<Math.ceil(seconds*60);i++)m.update(1/60,input);};
function arena(){const m=new Combat();m.enemies=[];m.player.x=0;m.player.z=0;m.player.angle=0;m.spawn('raider',0,1.3);m.enemies[0].stagger=100;m.shard.z=-20;return m;}
test('each basic swing hits a target once, only in its active window',()=>{const m=arena();m.startAttack();step(m,.10);assert.equal(m.enemies[0].hp,100);step(m,.24);assert.equal(m.enemies[0].hp,78);step(m,.1);assert.equal(m.enemies[0].hp,78);assert.equal(m.hits,1);});
test('three-hit combo progresses, strengthens finisher and times out',()=>{const m=arena();m.enemies=[];for(const combo of [1,2,3]){m.player.stamina=100;assert(m.startAttack());assert.equal(m.player.action.combo,combo);assert.equal(m.player.action.damage,22*(combo===3?1.5:1));step(m,.6);}step(m,1);assert(m.startAttack());assert.equal(m.player.action.combo,1);});
test('weapons distinguish thrust reach from sweep width',()=>{const p={x:0,z:0,angle:0};assert(inArc(p,{x:0,z:3},WEAPONS.spear.range,WEAPONS.spear.arc));assert(!inArc(p,{x:0,z:3},WEAPONS.sword.range,WEAPONS.sword.arc));assert(inArc(p,{x:1.5,z:1},WEAPONS.axe.range,WEAPONS.axe.arc));assert(!inArc(p,{x:1.5,z:1},WEAPONS.spear.range,WEAPONS.spear.arc));assert(!inArc(p,{x:0,z:-1},WEAPONS.sword.range,WEAPONS.sword.arc));});
test('cannot equip during a swing; cycle is sword, axe, spear',()=>{const m=arena();assert(m.cycleWeapon());assert.equal(m.player.weapon,'axe');assert(m.cycleWeapon());assert.equal(m.player.weapon,'spear');m.startAttack();assert.equal(m.cycleWeapon(),false);step(m,.7);assert(m.cycleWeapon());assert.equal(m.player.weapon,'sword');});
test('dodge cancels windup, protects briefly and consumes stamina',()=>{const m=arena();m.enemies=[];m.startAttack();assert(m.dodge(1,0));assert.equal(m.player.action,null);assert.equal(m.hurtPlayer(20),false);step(m,.35);assert(m.player.x>2);assert(m.hurtPlayer(20));assert.equal(m.player.hp,100);});
test('dodge does not cancel an active hit or work with insufficient stamina',()=>{const m=arena();m.startAttack();step(m,.18);assert.equal(m.phase,'active');assert.equal(m.dodge(0,1),false);m.player.action=null;m.player.stamina=24;assert.equal(m.dodge(0,1),false);});
test('skills apply costs and cooldowns; Battle Cry buffs and staggers',()=>{const m=arena();assert(m.startAttack('cry'));step(m,.22);assert(m.player.buff>0);assert(m.enemies[0].stagger>1);step(m,.35);const stamina=m.player.stamina;assert.equal(m.startAttack('cry'),false);assert.equal(m.player.stamina,stamina);assert.equal(m.skillsUsed.cry,1);assert(m.startAttack());assert.equal(m.player.action.damage,22*1.35);});
test('slam hits behind player and cannot bypass low stamina',()=>{const m=arena();m.enemies[0].z=-2;m.player.stamina=29;assert.equal(m.startAttack('slam'),false);m.player.stamina=100;assert(m.startAttack('slam'));step(m,.55);assert.equal(m.enemies[0].hp,68);assert(m.enemies[0].stagger>.9);});
test('shard spawns exactly two waves; delayed blast hurts both sides',()=>{const m=arena();m.enemies=[];m.shard.x=0;m.shard.z=0;m.player.x=1;m.damageShard(251);assert.equal(m.enemies.length,4);assert(!m.shard.exploded);step(m,.5);assert(!m.shard.exploded);m.enemies.forEach(e=>e.stagger=100);step(m,1);assert(m.shard.exploded);assert(m.damageTaken>=38);assert(m.kills>=2);m.damageShard(20);assert.equal(m.enemies.length,4);});
test('enemies telegraph and can be evaded before attack lands',()=>{const m=arena();const e=m.enemies[0];m.player.z=-30;e.z=e.homeZ=-28.7;e.stagger=0;step(m,.05);assert.equal(e.phase,'windup');assert.equal(m.player.hp,120);m.player.z=-34;step(m,1);assert.equal(m.player.hp,120);});
test('movement respects collision and slides along blocked axis',()=>{const m=new Combat((x,z)=>x<=1);m.enemies=[];m.player.x=.99;m.player.z=11;step(m,1,{x:.7,z:-.7,aim:0});assert(m.player.x<=1);assert(m.player.z<9);});
test('death blocks actions; reset fully restores encounter',()=>{const m=arena();m.player.hp=1;m.hurtPlayer(10);assert(m.dead);assert.equal(m.startAttack(),false);m.reset();assert.equal(m.player.hp,120);assert.equal(m.guardians.length,20);assert.equal(m.kills,0);assert.equal(m.shard.hp,250);assert(!m.dead);});
test('victory requires the shard explosion AND every guardian, not just the initial enemies',()=>{const m=new Combat();for(const e of m.guardians)m.damageEnemy(e,1000);assert(!m.complete);m.damageShard(251);assert.equal(m.guardians.length,24);assert(!m.complete);m.enemies.forEach(e=>e.stagger=100);step(m,1.5);assert(m.shard.exploded);assert(!m.complete);for(const e of m.enemies)m.damageEnemy(e,1000);assert(m.complete);assert.equal(m.kills,24);m.reset();assert(!m.complete);assert.equal(m.skillsUsed.cry,0);});
test('safe ground restores health, combat ground does not; buffs expire',()=>{const m=new Combat();m.enemies=[];m.player.hp=60;step(m,1);assert(Math.abs(m.player.hp-68)<.01);m.player.z=-25;step(m,1);assert(Math.abs(m.player.hp-68)<.01);m.startAttack('cry');step(m,7);assert.equal(m.player.buff,0);assert(m.player.cooldowns.cry>0);});
