// Art-only fixtures; camera placement is not a traversal or combat claim.
import puppeteer from 'puppeteer';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='_artifacts/geography/art';await fs.mkdir(out,{recursive:true});
const browser=await puppeteer.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(String(r.status())+' '+r.url());});await page.setViewport({width:1100,height:760});await page.setRequestInterception(true);page.on('request',r=>r.url().endsWith('/src/main.js')?r.respond({status:200,contentType:'text/javascript',body:''}):r.continue());await page.goto('http://localhost:4173/preview/');
 await page.evaluate(async()=>{const T=await import('three'),{createRig}=await import('./lib/rig.js'),{loadArt}=await import('./src/art.js'),{createWorld}=await import('./src/world.js'),{setLandscapeLighting}=await import('./src/landscape-lighting.js');document.body.innerHTML='';const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1100,760);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;document.body.append(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(44,1100/760,.1,140),rig=createRig(T,renderer,scene,{tier:'phone',post:false,cascades:1,shadowMap:1024,shadowDist:36,exposure:1.15,sunColor:0xffe6bd,sunIntensity:2.25,fill:1.3,envIntensity:.5,bounce:.4,fogStart:19,fogDensity:.022}),world=await createWorld(scene,await loadArt(renderer));await rig.ready;
 for(const [key,rgb] of Object.entries({Horizon:[.16,.23,.26],Low:[.13,.20,.24],Mid:[.08,.13,.18],High:[.05,.09,.14],Zenith:[.035,.065,.10],Haze:[.16,.23,.26],Below:[.06,.09,.08],SunGlow:[.2,.24,.25]}))rig.atmos[`uAtm${key}`].value.setRGB(...rgb);
 window.__artFrame=({region,view})=>{world.setRegion(region);setLandscapeLighting(rig,world.atmosphere);const views={river:[[-35,10,21],[-48,0,7]],highbank:[[-45,10,-24],[-52,1,-37]],forest:[[37,10,19],[50,0,8]],beach:[[34,10,30],[53,0,15]],jetty:[[44,8,19],[56,0,8]],tarn:[[31,11,52],[47,0,38]],mountains:[[-36,13,-12],[-54,7,-28]]};camera.position.fromArray(views[view][0]);camera.lookAt(...views[view][1]);rig.refresh(scene);world.update(.1,{x:views[view][1][0],z:views[view][1][2]});for(let i=0;i<3;i++)rig.render(camera,1/60);return {draws:renderer.info.render.calls,tris:renderer.info.render.triangles};};});
 const results=[];for(let region=0;region<4;region++)for(const view of [['river','highbank'],['forest'],['beach','jetty'],['tarn','mountains']][region]){const stats=await page.evaluate(o=>window.__artFrame(o),{region,view});await page.screenshot({path:`${out}/${region}-${view}.png`});results.push({region,view,...stats});console.log(results.at(-1));assert(stats.draws<=500);assert(stats.tris<=600000);}
 assert.deepEqual(errors,[]);await fs.writeFile(`${out}/art-review.json`,JSON.stringify({artFixture:true,results,errors},null,2));
}finally{await browser.close();}
